### ISSUE TITLE
[tracking] rollup_bundle API refactoring

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#826]
Should have an agreed design doc for updating rollup_bundle:

Requirements:

- [ ] Ability to use different bundle types (es2015, umd, cjs, …)
- [ ] Ability to use different language levels (es2015, es5)
- [ ] Ability to use minified bundles
- [ ] No unnecessary actions are run
- [ ] Full sourcemap support (correctly mapping to original source)
- [ ] Standalone @bazel/rollup npm package
- [ ] Users don't manually specify lazy-loaded additional entry points

Nice to have / future / open for debate:

- [ ] Custom rollup plugin support
- [ ] Base rollup config input
- [x] Standalone terser rule
- [ ] Standalone downlevel/to-es5 rule

**Comment by gregmagolan** [comment]
Related:
terser runs across chunks in seria: https://github.com/bazelbuild/rules_nodejs/issues/822
`rollup_bundle` loses sourcemap context due to running tsc for downleveling: https://github.com/bazelbuild/rules_nodejs/issues/175

**Comment by alexeagle** [comment]
Done and released :taco:
